About branch fixes
ss-itacademy-251/LvivCompany.Bookstore pull request #19
Opened 2017-07-13 13:18 UTC by Torbins

2017-07-13 15:20 UTC, IUnknownPtr requested changes

2017-07-13 15:20 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Startup.cs
> +                    template: "{controller=About}/{action=About}");
Use generic route template for all controllers. Don't hard code values here

2017-07-13 15:20 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/wwwroot/css/SideBarrStyle.css
> +.MainContent {
use lower case naming for class names like `main` or `main-content`

2017-07-17 13:17 UTC, Torbins commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Startup.cs
> -            app.Run(async (context) =>
Цей ран напевно спочатку треба було пофіксати окремим комітом, а уже потім видалити

2017-07-17 13:22 UTC, Torbins commented
Everything seems to be ok now

2017-07-17 13:46 UTC, IUnknownPtr requested changes

2017-07-17 13:46 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Shared/_Layout.cshtml
> +                    <li class="container-fluid"><a href="@Url.RouteUrl(new { controller = "About", action = "About" })">About us</a></li>
Use anchor tag helper instead

2017-07-17 13:46 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Startup.cs
> +        //public IConfiguration Configuration { get; }
Keep your code clean. Remove code if it's not required, don't comment it. Use comments only for documentation purposes.

2017-07-18 15:12 UTC, Torbins commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Shared/_Layout.cshtml
> +                    <li class="container-fluid"><a href="@Url.RouteUrl(new { controller = "About", action = "About" })">About us</a></li>
Fixed

2017-07-18 15:18 UTC, Torbins commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Startup.cs
> +        //public IConfiguration Configuration { get; }
Done.

2017-07-19 09:12 UTC, IUnknownPtr requested changes
Please resolve conflicts

2017-07-19 10:49 UTC, Torbins commented
Conflicts resolved

2017-07-19 10:55 UTC, merged