Feature/identity roles
ss-itacademy-251/LvivCompany.Bookstore pull request #40
Opened 2017-07-27 12:12 UTC by stepaHricishin

Seurity with part of Edit profile

2017-07-28 09:40 UTC, IUnknownPtr requested changes

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Controllers/AccountController.cs
>                      if (!String.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
Use `string` instead of `String`

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Account/Login.cshtml.orig
> +<<<<<<< HEAD
Remove this file

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Account/Register.cshtml.orig
> +<<<<<<< HEAD
Remove this file

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Shared/_Layout.cshtml
> +<body style="font-family:'Franklin Gothic'">
Don't inline CSS styles

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/_ViewImports.cshtml.orig
> +﻿@using LvivCompany.Bookstore.Web
Remove this file

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Shared/_PartialLogin.cshtml
> +      <button class="btn btn-link btn-group " asp-controller="Account" asp-action="LogOff"/><span class="glyphicon glyphicon-log-out"> LogOut</span>
`button` requires a closing tag

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Shared/_PartialLogin.cshtml
> +        <a  class="btn btn-link btn-group" asp-controller="Account" asp-action="Profile"><span class="glyphicon glyphicon-user"> @_UserManager.GetUserName(User)</span> </a>
Extract into 2 partial views

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Shared/_PartialLogin.cshtml
> +﻿@using Microsoft.AspNetCore.Identity
move using directives to _ViewImports

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Account/Edit.cshtml
> +        Layout = "~/Views/Shared/_Layout.cshtml";
Layout is already defined in _ViewStart

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Account/Register.cshtml
> +
Remove this line to fix 404

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Account/Register.cshtml
> +                    <span asp-validation-for="Email"></span>
Apply some styles for validation messages
![validation messages](https://user-images.githubusercontent.com/6797885/28680920-6dc6b816-7300-11e7-85eb-e108ec48bac7.png)

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Account/Register.cshtml
> +                    <select asp-for="AppRoleId" asp-items="@Model.AppRoles" class="form-control">
There is no validation message here

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Controllers/AccountController.cs
> +            }
Don't create roles here

2017-07-28 09:40 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Account/Profile.cshtml
> +                <script type="text/javascript">
Don't inline JavaScript. Extract into external file

2017-08-01 19:07 UTC, IUnknownPtr requested changes

2017-08-01 19:07 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/appsettings.json
> +  "AdminUserSettings": {
Don't store secure information in source files

2017-08-01 19:07 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Account/Register.cshtml
>      <link href="~/css/RegLogStyle.css" rel="stylesheet" />
Use sections. See Anna's commit 95e0771

2017-08-01 19:07 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Account/Edit.cshtml
> +<link href="~/css/RegLogStyle.css" rel="stylesheet" />
Use sections. See Anna's commit 95e0771

2017-08-01 19:07 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Account/Edit.cshtml
> +<div class="container " style="padding-top: 0px;">
Move this style to CSS file

2017-08-01 19:07 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Controllers/AccountController.cs
> +        public User ModelToUser(EditProfileViewModel model, User tempUser)
Move to mapper classes like in 95e0771

2017-08-01 20:13 UTC, stepaHricishin commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Controllers/AccountController.cs
> +        public User ModelToUser(EditProfileViewModel model, User tempUser)
Це просто винести з контролера в окремий клас методи, 
чи так я в Ані  заюзати автомапер?

2017-08-09 11:01 UTC, IUnknownPtr requested changes
Ready to merge. Just rename IMapp back to IMapper and resolve conflicts

2017-08-09 14:19 UTC, IUnknownPtr requested changes

2017-08-09 14:19 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Shared/_Layout.cshtml
> +    @RenderSection("Scripts", false)
Scripts section should at the bottom of `body`

2017-08-09 14:19 UTC, IUnknownPtr commented on LvivCompany.Bookstore/LvivCompany.Bookstore.Web/Views/Shared/_Layout.cshtml
>      <script src="~/lib/jquery/dist/jquery.js"></script>
Also move all scripts to the bottom of body

2017-08-09 14:40 UTC, IUnknownPtr approved these changes

2017-08-09 14:41 UTC, merged